version: "3"
services:
  nginx-temp:
    container_name: nginx-temp
    image: nginx:alpine
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./etc/nginx/templates-initiate:/etc/nginx/templates
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
  certbot-temp:
    container_name: certbot-temp
    image: certbot/dns-cloudflare
    depends_on:
      - nginx-temp
    command: >- 
      certonly --reinstall --non-interactive
      --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare/.secrets
      --preferred-challenges dns-01
      --email ${EMAIL} --agree-tos --no-eff-email
      -d ${DOMAIN},*.${DOMAIN}
    volumes:
      - ./etc/cloudflare:/etc/cloudflare
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
