version: "3"
services:
  nginx-temp-server.fls.red:
    container_name: nginx-temp-server.fls.red
    image: nginx:alpine
    environment:
      - DOMAIN
    ports:
      - 80:80
    volumes:
      - ./etc/nginx/templates-initiate:/etc/nginx/templates
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
  certbot-temp-server.fls.red:
    container_name: certbot-temp-server.fls.red
    image: certbot/certbot:latest
    depends_on:
      - nginx-temp-server.fls.red
    command: >- 
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email ${EMAIL} --agree-tos --no-eff-email
      -d ${DOMAIN}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot
