version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/data:/var/www/certbot
    networks:
      - nginx-net
  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --non-interactive
      --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare/.secrets
      --email ${EMAIL} --agree-tos --no-eff-email
      --preferred-challenges dns-01
      -d ${DOMAIN},*.${DOMAIN}
    volumes:
      - ./etc/cloudflare:/etc/cloudflare
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

networks:
  nginx-net:
    external: true
